import '../styles/globals.css';
import { Montserrat } from 'next/font/google';
import { ClockProvider } from './components/context/ClockContext';
import { AlarmProvider } from './components/context/AlarmContext';

const monteserrat = Montserrat({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata = {
  title: 'Pomodorify',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${monteserrat.className} antialiased`}>
        <AlarmProvider>
          <ClockProvider>
            {children}
          </ClockProvider>
        </AlarmProvider>
      </body>
    </html>
  )
}
