import '../styles/globals.css';
import { Montserrat } from 'next/font/google';

const monteserrat = Montserrat({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata = {
  title: 'Music Clock Alarm',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${monteserrat.className} antialiased`}>{children}</body>
    </html>
  )
}
